Fixes error cloning gitlab and azure devops repositories
- Passes username into initialize-gitops.sh script and includes in the git url - closes #66
- Adds project variable for Azure DevOps repos - closes #68
- Sets the user.name and user.email values locally in the repository instead of globally - closes #65
- Cleans up cloned reposotory in exceptional situations - closes #54

Signed-off-by: Sean Sundberg <seansund@us.ibm.com>

diff --git a/.github/workflows/verify-workflow.yaml b/.github/workflows/verify-workflow.yaml
--- a/.github/workflows/verify-workflow.yaml
+++ b/.github/workflows/verify-workflow.yaml
@@ -4,13 +4,11 @@ name: Verify
 on:
   workflow_call:
     secrets:
-      IBMCLOUD_API_KEY:
-        required: true
-      GIT_ADMIN_USERNAME:
-        required: true
-      GIT_ADMIN_TOKEN:
+      GITU_CONFIG:
         required: true
       GIT_ORG:
+        required: false
+      GIT_PROJECT:
         required: false
 
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
@@ -22,9 +20,13 @@ jobs:
     strategy:
       matrix:
         testcase:
-          - ibm_ocp49
+          - github.com
+          - github.ibm.com
+          - us-south.git.cloud.ibm.com
+          - bitbucket.org
+          - dev.azure.com
+          - gitea-gitea.toolkit-dev410-2ab66b053c14936810608de9a1deac9c-0000.us-east.containers.appdomain.cloud
       fail-fast: false
-      max-parallel: 1
 
     env:
       HOME: /home/devops
@@ -38,38 +40,60 @@ jobs:
         name: Set up variables
         env:
           GIT_ORG: ${{ secrets.GIT_ORG }}
+          GITU_CONFIG: ${{ secrets.GITU_CONFIG }}
+          GIT_PROJECT: ${{ secrets.GIT_PROJECT }}
         shell: bash
         run: |
-          repo=$(echo ${GITHUB_REPOSITORY} | sed -E "s~.*/[^-]+-(.*)~\1~g")
+          repo=$(echo "${GITHUB_REPOSITORY}" | sed -E "s~.*/[^-]+-(.*)~\1~g")
           echo "Repo: $repo"
           echo "::set-output name=repo::$repo"
 
           org="${GIT_ORG:-cloud-native-toolkit-test}"
           echo "Org: $org"
           echo "::set-output name=org::$org"
+          
+          project="${GIT_PROJECT:-Test}"
+          echo "Project: $project"
+          echo "::set-output name=project::$project"          
+          
+          username=$(echo "${GITU_CONFIG}" |  yq '.credentials[] | select(.host == "${{ matrix.testcase }}") | .username')
+          echo "Username: $username"
+          if [[ -z "${username}" ]]; then
+            echo "Username config missing" >&2
+            exit 1
+          fi
+          echo "::set-output name=username::$username"
+          
+          token=$(echo "${GITU_CONFIG}" |  yq '.credentials[] | select(.host == "${{ matrix.testcase }}") | .token')
+          echo "Token: xxx"
+          if [[ -z "${token}" ]]; then
+            echo "Token config missing" >&2
+            exit 1
+          fi
+          echo "::set-output name=token::$token"
 
       - name: Verify deploy on ${{ matrix.testcase }}
         uses: cloud-native-toolkit/action-module-verify-deploy@main
         with:
-          clusterId: ${{ matrix.testcase }}
+          clusterId: "no-config"
           validateDeployScript: .github/scripts/validate-deploy.sh
         env:
-          TF_VAR_git_username: ${{ secrets.GIT_ADMIN_USERNAME }}
-          TF_VAR_git_token: ${{ secrets.GIT_ADMIN_TOKEN }}
+          TF_VAR_git_host: ${{ matrix.testcase }}
+          TF_VAR_git_username: ${{ steps.variables.outputs.username }}
+          TF_VAR_git_token: ${{ steps.variables.outputs.token }}
           TF_VAR_git_org: ${{ steps.variables.outputs.org }}
           TF_VAR_git_repo: ${{ steps.variables.outputs.repo }}
-          TF_VAR_ibmcloud_api_key: ${{ secrets.IBMCLOUD_API_KEY }}
-          IBMCLOUD_API_KEY: ${{ secrets.IBMCLOUD_API_KEY }}
+          TF_VAR_git_project: ${{ steps.variables.outputs.project }}
 
       - name: Verify destroy on ${{ matrix.testcase }}
         uses: cloud-native-toolkit/action-module-verify-destroy@main
         if: ${{ always() }}
         with:
-          clusterId: ${{ matrix.testcase }}
+          clusterId: "no-config"
         env:
-          TF_VAR_git_username: ${{ secrets.GIT_ADMIN_USERNAME }}
-          TF_VAR_git_token: ${{ secrets.GIT_ADMIN_TOKEN }}
+          TF_VAR_git_host: ${{ matrix.testcase }}
+          TF_VAR_git_username: ${{ steps.variables.outputs.username }}
+          TF_VAR_git_token: ${{ steps.variables.outputs.token }}
           TF_VAR_git_org: ${{ steps.variables.outputs.org }}
           TF_VAR_git_repo: ${{ steps.variables.outputs.repo }}
-          TF_VAR_ibmcloud_api_key: ${{ secrets.IBMCLOUD_API_KEY }}
-          IBMCLOUD_API_KEY: ${{ secrets.IBMCLOUD_API_KEY }}
+          TF_VAR_git_project: ${{ steps.variables.outputs.project }}
